### PR TITLE
First draft revision

### PR DESCRIPTION
**Pull request by anwala**
Hello @Greatness-2003,

Fantastic job you've done for the first draft! Thank you. I've completed my first draft revision. Kindly review my revision and merge. Also, would it be possible to include a clean version of our evaluation code?

Respectfully,

@anwala

### CODE REVIEW

**Comment by Greatness-2003** [comment]
Hi Professor,

Merry Christmas!!

I'll take a look at the revisions soon. Can you clarify on what evaluation
code you're referring to? I already included the code for the
traditional geoparsers and LLMs.

Greatness.

**Comment by anwala** [comment]
Merry Christmas @Greatness-2003 

In [evaluation process](https://github.com/wm-newslab/toponym-disambiguation?tab=readme-ov-file#evaluation-process), I linked to [evaluation.py](https://github.com/wm-newslab/toponym-disambiguation/blob/main/eval/evaluation.py) which doesn't exist.

Can we provide this code?

**Comment by Greatness-2003** [comment]
@anwala 

For the traditional geoparsers, the evaluation function is contained within the python file for each of them. because the geoparsers function differently (and have different requirements), there isn't a general evaluation script that works for all of them.

As for the LLMs, I have included the evaluation script I used for all of them. you can find it under the models/llms folder: [models/llms/evaluate_llm_disambiguation.py](https://github.com/wm-newslab/toporesolve/blob/1efdeefd0494bd9bd84a0d9433ed494d894c44af/models/llms/evaluate_llm_disambiguation.py)

**Comment by anwala** [comment]
I see thanks!

**Pull request merged**
